#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "#include \"kernel/syscall.h\"\n";


print "# generated by usys.pl - do not edit\n";



sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("pause");
entry("uptime");

entry("msgget");
entry("msgsnd");
entry("msgrcv");
entry("msgctl");
entry("sleep");

print "# Automatically generated by usys.PL - do not edit\n";
